/*
 * JEDEC PUBLICATION 
 * Standard Manufacture's Identification Code 
 * JEP106N (Revision of JEP106M) DECEMBER 2003 @ www.jedec.org
 * Published by ©JEDEC Solid State Technology Association 2003
 * 2500 Wilson Boulevard
 * Arlington, VA 22201-3834
 * This document may be downloaded free of charge, however EIA retains the
 * copyright on this material. By downloading this file the individual agrees not to
 * charge for or resell the resulting material.
 */

struct jedec_vendor {
	char string[48]; /*47 by largest till now*/
};

struct jedec_vendor jedec_vendor[] = {
/* Table 1 - Manufacturer's Identification Code */
/*  0*/ {"invalid (Start of Table 1)"},
/*  1*/ {"AMD"},
/*  2*/ {"AMI"},
/*  3*/ {"Fairchild"},
/*  4*/ {"Fujitsu"},
/*  5*/ {"GTE"},
/*  6*/ {"Harris"},
/*  7*/ {"Hitachi"},
/*  8*/ {"Inmos"},
/*  9*/ {"Intel"},
/* 10*/ {"I.T.T."},
/* 11*/ {"Intersil"},
/* 12*/ {"Monolithic Memories"},
/* 13*/ {"Mostek"},
/* 14*/ {"Motorola"},
/* 15*/ {"National"},
/* 16*/ {"NEC"},
/* 17*/ {"RCA"},
/* 18*/ {"Raytheon"}, 
/* 19*/ {"Conexant (Rockwell)"},
/* 20*/ {"Seeq"},
/* 21*/ {"Philips Semi. (Signetics)"},
/* 22*/ {"Synertek"},
/* 23*/ {"Texas Instruments"},
/* 24*/ {"Toshiba"},
/* 25*/ {"Xicor"},
/* 26*/ {"Zilog"},
/* 27*/ {"Eurotechnique"},
/* 28*/ {"Mitsubishi"},
/* 29*/ {"Lucent (AT&T)"},
/* 30*/ {"Exel"},
/* 31*/ {"Atmel"},
/* 32*/ {"SGS/Thomson"},
/* 33*/ {"Lattice Semiconductor"},
/* 34*/ {"NCR"},
/* 35*/ {"Wafer Scale Integration"},
/* 36*/ {"IBM"},
/* 37*/ {"Tristar"},
/* 38*/ {"Visic"},
/* 39*/ {"Intl. CMOS Technology"},
/* 40*/ {"SSSI"},
/* 41*/ {"Microchip Technology"},
/* 42*/ {"Ricoh Ltd."},
/* 43*/ {"VLSI"},
/* 44*/ {"Micron Technology"},
/* 45*/ {"Hyundai Electronics"},
/* 46*/ {"OKI Semiconductor"},
/* 47*/ {"ACTEL"},
/* 48*/ {"Sharp"},
/* 49*/ {"Catalyst"},
/* 50*/ {"Panasonic"},
/* 51*/ {"IDT"},
/* 52*/ {"Cypress"},
/* 53*/ {"DEC"},
/* 54*/ {"LSI Logic"},
/* 55*/ {"Zarlink (formerly Plessey)"},
/* 56*/ {"UTMC"},
/* 57*/ {"Thinking Machine"},
/* 58*/ {"Thomson CSF"},
/* 59*/ {"Integrated CMOS(Vertex)"},
/* 60*/ {"Honeywell"},
/* 61*/ {"Tektronix"},
/* 62*/ {"Sun Microsystems"},
/* 63*/ {"SST"},
/* 64*/ {"MOSEL"},
/* 65*/ {"Infineon (formerly Siemens)"},
/* 66*/ {"Macronix"}, 
/* 67*/ {"Xerox"},
/* 68*/ {"Plus Logic"},
/* 69*/ {"SunDisk"},
/* 70*/ {"Elan Circuit Tech."},
/* 71*/ {"European Silicon Str."},
/* 72*/ {"Apple Computer"}, 
/* 73*/ {"Xilinx"},
/* 74*/ {"Compaq"},
/* 75*/ {"Protocol Engines"},
/* 76*/ {"SCI"},
/* 77*/ {"Seiko Instruments"},
/* 78*/ {"Samsung"},
/* 79*/ {"I3 Design System"},
/* 80*/ {"Klic"},
/* 81*/ {"Crosspoint Solutions"},
/* 82*/ {"Alliance Semiconductor"},
/* 83*/ {"Tandem"},
/* 84*/ {"Hewlett-Packard"},
/* 85*/ {"Intg. Silicon Solutions"}, 
/* 86*/ {"Brooktree"},
/* 87*/ {"New Media"},
/* 88*/ {"MHS Electronic"},
/* 89*/ {"Performance Semi."},
/* 90*/ {"Winbond Electronic"},
/* 91*/ {"Kawasaki Steel"},
/* 92*/ {"Bright Micro"},
/* 93*/ {"TECMAR"},
/* 94*/ {"Exar"},
/* 95*/ {"PCMCIA"},
/* 96*/ {"LG Semiconductor"},
/* 97*/ {"Northern Telecom"},
/* 98*/ {"Sanyo"},
/* 99*/ {"Array Microsystems"},
/*100*/ {"Crystal Semiconductor"},
/*101*/ {"Analog Devices"},
/*102*/ {"PMC-Sierra"},
/*103*/ {"Asparix"}, 
/*104*/ {"Convex Computer"},
/*105*/ {"Quality Semiconductor"},
/*106*/ {"Nimbus Technology"},
/*107*/ {"Transwitch"},
/*108*/ {"Micronas (ITT Intermetall)"},
/*109*/ {"Cannon"},
/*110*/ {"Altera"},
/*111*/ {"NEXCOM"},
/*112*/ {"QUALCOMM"},
/*113*/ {"Sony"},
/*114*/ {"Cray Research"},
/*115*/ {"AMS(Austria Micro)"},
/*116*/ {"Vitesse"}, 
/*117*/ {"Aster Electronics"},
/*118*/ {"Bay Networks(Synoptic)"},
/*119*/ {"Zentrum or ZMD"},
/*120*/ {"TRW"},
/*121*/ {"Thesys"},
/*122*/ {"Solbourne Computer"},
/*123*/ {"Allied-Signal"},
/*124*/ {"Dialog"},
/*125*/ {"Media Vision"},
/*126*/ {"Level One Communication"},
/*127*/ {"invalid -- Continuation Code (End of Table 1)"},
/*********************************************************************************/
/* Table 2 - Manufacturer's Identification Code */
/*128*/ {"invalid (Start of Table 2)"},
/*129*/ {"Cirrus Logic"},
/*130*/ {"National Instruments"},
/*131*/ {"ILC Data Device"},
/*132*/ {"Alcatel Mietec"},
/*133*/ {"Micro Linear"},
/*134*/ {"Univ. of NC"},
/*135*/ {"JTAG Technologies"},
/*136*/ {"Loral"},
/*136*/ {"Nchip"},
/*137*/ {"Galileo Tech"},
/*138*/ {"Bestlink Systems"},
/*139*/ {"Graychip"},
/*140*/ {"GENNUM"},
/*141*/ {"VideoLogic"},
/*142*/ {"Robert Bosch"},
/*143*/ {"Chip Express"},
/*144*/ {"DATARAM"},
/*145*/ {"United Microelec Corp."},
/*146*/ {"TCSI"},
/*147*/ {"Smart Modular"},
/*148*/ {"Hughes Aircraft"},
/*149*/ {"Lanstar Semiconductor"},
/*150*/ {"Qlogic"},
/*151*/ {"Kingston"},
/*152*/ {"Music Semi"},
/*153*/ {"Ericsson Components"},
/*154*/ {"SpaSE"},
/*155*/ {"Eon Silicon Devices"}, 
/*156*/ {"Programmable Micro Corp"},
/*157*/ {"DoD"}, 
/*158*/ {"Integ. Memories Tech."},
/*159*/ {"Corollary Inc."},
/*160*/ {"Dallas Semiconductor"},
/*161*/ {"Omnivision"},
/*162*/ {"EIV(Switzerland)"},
/*163*/ {"Novatel Wireless"},
/*164*/ {"Zarlink (formerly Mitel)"},
/*165*/ {"Clearpoint"},
/*166*/ {"Cabletron"},
/*167*/ {"Silicon Technology"},
/*168*/ {"Vanguard"},
/*169*/ {"Hagiwara Sys-Com"},
/*170*/ {"Vantis"},
/*171*/ {"Celestica"},
/*172*/ {"Century"},
/*173*/ {"Hal Computers"},
/*174*/ {"Rohm Company Ltd."},
/*175*/ {"Juniper Networks"},
/*176*/ {"Libit Signal Processing"},
/*177*/ {"Enhanced Memories Inc."},
/*178*/ {"Tundra Semiconductor"},
/*179*/ {"Adaptec Inc."},
/*180*/ {"LightSpeed Semi."},
/*181*/ {"ZSP Corp."},
/*182*/ {"AMIC Technology"},
/*183*/ {"Adobe Systems"},
/*184*/ {"Dynachip"},
/*185*/ {"PNY Electronics"},
/*186*/ {"Newport Digital"},
/*187*/ {"MMC Networks"},
/*189*/ {"T Square"},
/*190*/ {"Seiko Epson"},
/*191*/ {"Broadcom"},
/*192*/ {"Viking Components"},
/*193*/ {"V3 Semiconductor"},
/*194*/ {"Flextronics (formerly Orbit)"},
/*195*/ {"Suwa Electronics"},
/*196*/ {"Transmeta"},
/*197*/ {"Micron CMS"},
/*198*/ {"American Computer & Digital Components Inc"},
/*199*/ {"Enhance 3000 Inc"},
/*200*/ {"Tower Semiconductor"},
/*201*/ {"CPU Design"},
/*202*/ {"Price Point"}, 
/*203*/ {"Maxim Integrated Product"},
/*204*/ {"Tellabs"},
/*205*/ {"Centaur Technology"},
/*206*/ {"Unigen Corporation"},
/*207*/ {"Transcend Information"},
/*208*/ {"Memory Card Technology"},
/*209*/ {"CKD Corporation Ltd."},
/*210*/ {"Capital Instruments, Inc."},
/*211*/ {"Aica Kogyo, Ltd."},
/*212*/ {"Linvex Technology"},
/*213*/ {"MSC Vertriebs GmbH"},
/*214*/ {"AKM Company, Ltd."},
/*215*/ {"Dynamem, Inc."},
/*216*/ {"NERA ASA"},
/*217*/ {"GSI Technology"},
/*218*/ {"Dane-Elec (C Memory)"},
/*219*/ {"Acorn Computers"},
/*220*/ {"Lara Technology"},
/*221*/ {"Oak Technology, Inc."},
/*222*/ {"Itec Memory"}, 
/*223*/ {"Tanisys Technology"},
/*224*/ {"Truevision"}, 
/*225*/ {"Wintec Industries"},
/*226*/ {"Super PC Memory"},
/*227*/ {"MGV Memory"},
/*228*/ {"Galvantech"},
/*229*/ {"Gadzoox Nteworks"},
/*230*/ {"Multi Dimensional Cons."},
/*231*/ {"GateField"},
/*232*/ {"Integrated Memory System"},
/*233*/ {"Triscend"},
/*234*/ {"XaQti"},
/*235*/ {"Goldenram"},
/*236*/ {"Clear Logic"}, 
/*237*/ {"Cimaron Communications"},
/*238*/ {"Nippon Steel Semi. Corp."},
/*239*/ {"Advantage Memory"},
/*240*/ {"AMCC"},
/*241*/ {"LeCroy"},
/*242*/ {"Yamaha Corporation"},
/*243*/ {"Digital Microwave"},
/*244*/ {"NetLogic Microsystems"},
/*245*/ {"MIMOS Semiconductor"},
/*246*/ {"Advanced Fibre"},
/*247*/ {"BF Goodrich Data."},
/*248*/ {"Epigram"},
/*249*/ {"Acbel Polytech Inc."},
/*251*/ {"Apacer Technology"},
/*251*/ {"Admor Memory"},
/*252*/ {"FOXCONN"},
/*253*/ {"Quadratics Superconductor"},
/*254*/ {"3COM"},
/*255*/ {"invalid -- Continuation Code (End of Table 2)"},
/*********************************************************************************/
/* Table 3 - Manufacturer's Identification Code */
/*256*/ {"invalid (Start of Table 3)"},
/*257*/ {"Camintonn Corporation"},
/*258*/ {"ISOA Incorporated"},
/*259*/ {"Agate Semiconductor"},
/*260*/ {"ADMtek Incorporated"},
/*261*/ {"HYPERTEC"},
/*262*/ {"Adhoc Technologies"},
/*263*/ {"MOSAID Technologies"},
/*264*/ {"Ardent Technologies"},
/*265*/ {"Switchcore"},
/*266*/ {"Cisco Systems, Inc."},
/*267*/ {"Allayer Technologies"},
/*268*/ {"WorkX AG"},
/*269*/ {"Oasis Semiconductor"},
/*270*/ {"Novanet Semiconductor"},
/*271*/ {"E-M Solutions"},
/*272*/ {"Power General"},
/*273*/ {"Advanced Hardware Arch."},
/*274*/ {"Inova Semiconductors GmbH"},
/*275*/ {"Telocity"},
/*276*/ {"Delkin Devices"},
/*277*/ {"Symagery Microsystems"},
/*278*/ {"C-Port Corporation"},
/*279*/ {"SiberCore Technologies"},
/*280*/ {"Southland Microsystems"},
/*281*/ {"Malleable Technologies"},
/*282*/ {"Kendin Communications"},
/*283*/ {"Great Technology Microcomputer"},
/*284*/ {"Sanmina Corporation"},
/*285*/ {"HADCO Corporation"},
/*286*/ {"Corsair"},
/*287*/ {"Actrans System Inc."},
/*288*/ {"ALPHA Technologies"},
/*289*/ {"Cygnal Integrated Products Incorporated"},
/*290*/ {"Artesyn Technologies"},
/*291*/ {"Align Manufacturing"},
/*292*/ {"Peregrine Semiconductor"},
/*293*/ {"Chameleon Systems"},
/*294*/ {"Aplus Flash Technology"},
/*295*/ {"MIPS Technologies"},
/*296*/ {"Chrysalis ITS"},
/*297*/ {"ADTEC Corporation"},
/*298*/ {"Kentron Technologies"},
/*299*/ {"Win Technologies"},
/*300*/ {"ASIC Designs Inc"},
/*301*/ {"Extreme Packet Devices"},
/*302*/ {"RF Micro Devices"},
/*303*/ {"Siemens AG"},
/*304*/ {"Sarnoff Corporation"},
/*305*/ {"Itautec Philco SA"},
/*306*/ {"Radiata Inc."},
/*307*/ {"Benchmark Elect. (AVEX)"},
/*308*/ {"Legend"},
/*309*/ {"SpecTek Incorporated"},
/*310*/ {"Hi/fn"},
/*311*/ {"Enikia Incorporated"},
/*312*/ {"SwitchOn Networks"},
/*313*/ {"AANetcom Incorporated"},
/*314*/ {"Micro Memory Bank"},
/*315*/ {"ESS Technology"},
/*316*/ {"Virata Corporation"},
/*317*/ {"Excess Bandwidth"},
/*318*/ {"West Bay Semiconductor"},
/*319*/ {"DSP Group"},
/*320*/ {"Newport Communications"},
/*321*/ {"Chip2Chip Incorporated"},
/*322*/ {"Phobos Corporation"},
/*323*/ {"Intellitech Corporation"},
/*324*/ {"Nordic VLSI ASA"},
/*325*/ {"Ishoni Networks"},
/*326*/ {"Silicon Spice"},
/*327*/ {"Alchemy Semiconductor"},
/*328*/ {"Agilent Technologies"},
/*329*/ {"Centillium Communications"},
/*330*/ {"W.L. Gore"},
/*331*/ {"HanBit Electronics"},
/*332*/ {"GlobeSpan"},
/*333*/ {"Element 14"},
/*334*/ {"Pycon"},
/*335*/ {"Saifun Semiconductors"},
/*336*/ {"Sibyte, Incorporated"},
/*337*/ {"MetaLink Technologies"},
/*338*/ {"Feiya Technology"},
/*339*/ {"I & C Technology"},
/*340*/ {"Shikatronics"},
/*341*/ {"Elektrobit"},
/*342*/ {"Megic"},
/*343*/ {"Com-Tier"},
/*344*/ {"Malaysia Micro Solutions"},
/*345*/ {"Hyperchip"},
/*346*/ {"Gemstone Communications"},
/*347*/ {"Anadyne Microelectronics"},
/*348*/ {"3ParData"},
/*349*/ {"Mellanox Technologies"},
/*350*/ {"Tenx Technologies"},
/*351*/ {"Helix AG"},
/*352*/ {"Domosys"},
/*353*/ {"Skyup Technology"},
/*354*/ {"HiNT Corporation"},
/*355*/ {"Chiaro"},
/*356*/ {"MCI Computer GMBH"},
/*357*/ {"Exbit Technology A/S"},
/*358*/ {"Integrated Technology Express"},
/*359*/ {"AVED Memory"},
/*360*/ {"Legerity"},
/*361*/ {"Jasmine Networks"},
/*362*/ {"Caspian Networks"},
/*363*/ {"nCUBE"},
/*364*/ {"Silicon Access Networks"},
/*365*/ {"FDK Corporation"},
/*366*/ {"High Bandwidth Access"},
/*367*/ {"MultiLink Technology"},
/*368*/ {"BRECIS"},
/*369*/ {"World Wide Packets"},
/*370*/ {"APW"},
/*371*/ {"Chicory Systems"},
/*372*/ {"Xstream Logic"},
/*373*/ {"Fast-Chip"},
/*374*/ {"Zucotto Wireless"},
/*375*/ {"Realchip"},
/*376*/ {"Galaxy Power"},
/*377*/ {"eSilicon"},
/*378*/ {"Morphics Technology"},
/*379*/ {"Accelerant Networks"},
/*380*/ {"Silicon Wave"},
/*381*/ {"SandCraft"},
/*382*/ {"Elpida"},
/*383*/ {"invalid -- Continuation Code (End of Table 3)"},
/*********************************************************************************/
/* Table 4 - Manufacturer's Identification Code */
/*384*/ {"invalid (Start of Table 4)"},
/*385*/ {"Solectron"},
/*386*/ {"Optosys Technologies"},
/*387*/ {"Buffalo (Formerly Melco)"},
/*389*/ {"TriMedia Technologies"},
/*390*/ {"Cyan Technologies"},
/*391*/ {"Global Locate"},
/*392*/ {"Optillion"},
/*393*/ {"Terago Communications"},
/*394*/ {"Ikanos Communications"},
/*395*/ {"Princeton Technology"},
/*396*/ {"Nanya Technology"},
/*397*/ {"Elite Flash Storage"},
/*398*/ {"Mysticom"},
/*399*/ {"LightSand Communications"},
/*400*/ {"ATI Technologies"},
/*401*/ {"Agere Systems"},
/*402*/ {"NeoMagic"},
/*403*/ {"AuroraNetics"},
/*404*/ {"Golden Empire"},
/*405*/ {"Muskin"},
/*406*/ {"Tioga Technologies"},
/*407*/ {"Netlist"},
/*408*/ {"TeraLogic"},
/*409*/ {"Cicada Semiconductor"},
/*410*/ {"Centon Electronics"},
/*411*/ {"Tyco Electronics"},
/*412*/ {"Magis Works"},
/*413*/ {"Zettacom"},
/*414*/ {"Cogency Semiconductor"},
/*415*/ {"Chipcon AS"},
/*416*/ {"Aspex Technology"},
/*417*/ {"F5 Networks"},
/*418*/ {"Programmable Silicon Solutions"},
/*419*/ {"ChipWrights"},
/*420*/ {"Acorn Networks"},
/*421*/ {"Quicklogic"},
/*422*/ {"Kingmax Semiconductor"},
/*423*/ {"BOPS"},
/*424*/ {"Flasys"},
/*425*/ {"BitBlitz Communications"},
/*426*/ {"eMemory Technology"},
/*427*/ {"Procket Networks"},
/*428*/ {"Purple Ray"},
/*429*/ {"Trebia Networks"},
/*430*/ {"Delta Electronics"},
/*431*/ {"Onex Communications"},
/*432*/ {"Ample Communications"},
/*433*/ {"Memory Experts Intl"},
/*434*/ {"Astute Networks"},
/*435*/ {"Azanda Network Devices"},
/*436*/ {"Dibcom"},
/*437*/ {"Tekmos"},
/*438*/ {"API NetWorks"},
/*439*/ {"Bay Microsystems"},
/*440*/ {"Firecron Ltd"},
/*441*/ {"Resonext Communications"},
/*442*/ {"Tachys Technologies"},
/*443*/ {"Equator Technology"},
/*444*/ {"Concept Computer"},
/*445*/ {"SILCOM"},
/*446*/ {"3Dlabs"},
/*447*/ {"c’t Magazine"},
/*448*/ {"Sanera Systems"},
/*449*/ {"Silicon Packets"},
/*450*/ {"Viasystems Group"},
/*451*/ {"Simtek"},
/*452*/ {"Semicon Devices Singapore"},
/*453*/ {"Satron Handelsges"},
/*454*/ {"Improv Systems"},
/*455*/ {"INDUSYS GmbH"},
/*456*/ {"Corrent"},
/*457*/ {"Infrant Technologies"},
/*458*/ {"Ritek Corp"},
/*459*/ {"empowerTel Networks"},
/*460*/ {"Hypertec"},
/*461*/ {"Cavium Networks"},
/*462*/ {"PLX Technology"},
/*463*/ {"Massana Design"},
/*464*/ {"Intrinsity"},
/*465*/ {"Valence Semiconductor"},
/*466*/ {"Terawave Communications"},
/*467*/ {"IceFyre Semiconductor"},
/*468*/ {"Primarion"},
/*469*/ {"Picochip Designs Ltd"},
/*470*/ {"Silverback Systems"},
/*471*/ {"Jade Star Technologies"},
/*472*/ {"Pijnenburg Securealink"},
/*473*/ {"MemorySolutioN"},
/*474*/ {"Cambridge Silicon Radio"},
/*475*/ {"Swissbit"},
/*476*/ {"Nazomi Communications"},
/*477*/ {"eWave System"},
/*478*/ {"Rockwell Collins"},
/*479*/ {"PAION"},
/*480*/ {"Alphamosaic Ltd"},
/*481*/ {"Sandburst"},
/*482*/ {"SiCon Video"},
/*483*/ {"NanoAmp Solutions"},
/*484*/ {"Ericsson Technology"},
/*485*/ {"PrairieComm"},
/*486*/ {"Mitac International"},
/*487*/ {"Layer N Networks"},
/*488*/ {"Atsana Semiconductor"},
/*489*/ {"Allegro Networks"},
/*490*/ {"Marvell Semiconductors"},
/*491*/ {"Netergy Microelectronic"},
/*492*/ {"NVIDIA"},
/*493*/ {"Internet Machines"},
/*494*/ {"Peak Electronics"},
/*495*/ {"Accton Technology"},
/*496*/ {"Teradiant Networks"},
/*497*/ {"Europe Technologies"},
/*498*/ {"Cortina Systems"},
/*499*/ {"RAM Components"},
/*500*/ {"Raqia Networks"},
/*501*/ {"ClearSpeed"},
/*502*/ {"Matsushita Battery"},
/*503*/ {"Xelerated"},
/*504*/ {"SimpleTech"},
/*505*/ {"Utron Technology"},
/*506*/ {"Astec International"},
/*507*/ {"AVM gmbH"},
/*508*/ {"Redux Communications"},
/*509*/ {"Dot Hill Systems"},
/*510*/ {"TeraChip"},
/*511*/ {"invalid -- Continuation Code (End of Table 4)"},
/*********************************************************************************/
/* Table 5 - Manufacturer's Identification Code */
/*512*/ {"invalid (Start of Table 5)"},
/*513*/ {"T-RAM Incorporated"},
/*514*/ {"Innovics Wireless"},
/*515*/ {"Teknovus"},
/*516*/ {"KeyEye Communications"},
/*517*/ {"Runcom Technologies"},
/*518*/ {"RedSwitch"},
/*519*/ {"Dotcast"},
/*520*/ {"Silicon Mountain Memory"},
/*521*/ {"Signia Technologies"},
/*522*/ {"Pixim"},
/*523*/ {"Galazar Networks"},
/*524*/ {"White Electronic Designs"},
/*525*/ {"Patriot Scientific"},
/*526*/ {"Neoaxiom Corporation"},
/*527*/ {"3Y Power Technology"},
/*528*/ {"Europe Technologies"},
/*529*/ {"Potentia Power Systems"},
/*530*/ {"C-guys Incorporated"},
/*531*/ {"Digital Communications Technology Incorporated"},
/*532*/ {"Silicon-Based Technology"},
/*533*/ {"Fulcrum Microsystems"},
/*534*/ {"Positivo Informatica Ltd"},
/*535*/ {"XIOtech Corporation"},
/*536*/ {"PortalPlayer"},
/*537*/ {"Zhiying Software"},
/*538*/ {"Direct2Data"},
/*539*/ {"Phonex Broadband"},
/*540*/ {"Skyworks Solutions"},
/*541*/ {"Entropic Communications"},
/*542*/ {"Pacific Force Technology"},
/*543*/ {"Zensys A/S"},
/*544*/ {"Legend Silicon Corp."},
/*545*/ {"sci-worx GmbH"},
/*546*/ {"Oasis Silicon Systems"},
/*547*/ {"Renesas Technology"},
/*548*/ {"Raza Microelectronics"},
/*549*/ {"Phyworks"},
/*550*/ {"MediaTek"},
/*551*/ {"Non-cents Productions"},
/*552*/ {"US Modular"},
/*553*/ {"Wintegra Ltd"},
/*554*/ {"Mathstar"},
/*555*/ {"StarCore"},
/*556*/ {"Oplus Technologies"},
/*557*/ {"Mindspeed"},
/*558*/ {"Just Young Computer"},
/*558*/ {"Radia Communications"},
/*560*/ {"OCZ"},
/*561*/ {"Emuzed"},
/*562*/ {"LOGIC Devices"},
/*563*/ {"Inphi Corporation"},
/*564*/ {"Quake Technologies"},
/*565*/ {"Vixel"},
/*566*/ {"SolusTek"},
/*567*/ {"Kongsberg Maritime"},
/*568*/ {"Faraday Technology"},
/*569*/ {"Altium Ltd."},
/*570*/ {"Insyte"},
/*571*/ {"ARM Ltd."},
/*572*/ {"DigiVision"},
/*573*/ {"Vativ Technologies"},
/*574*/ {"Endicott Interconnect Technologies"},
/*575*/ {"Pericom"},
/*576*/ {"Bandspeed"},
/*577*/ {"LeWiz Communications"},
/*578*/ {"CPU Technology"},
/*579*/ {"Ramaxel Technology"},
/*580*/ {"DSP Group"},
/*581*/ {"Axis Communications"},
/*582*/ {"Legacy Electronics"},
/*583*/ {"Chrontel"},
/*584*/ {"Powerchip Semiconductor"},
/*585*/ {"MobilEye Technologies"},
/*586*/ {"Excel Semiconductor"},
/*587*/ {"A-DATA Technology"},
/*588*//*76*/ {"VirtualDigm"},
/* As of December 2, 2003 */
};

